<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 */

$root_dir = dirname(__DIR__);
$webroot_dir = __DIR__;

// Load Composer autoload
if (file_exists($root_dir . '/vendor/autoload.php')) {
    require_once $root_dir . '/vendor/autoload.php';
}

// Load application bootstrap (env vars + constants)
if (file_exists($root_dir . '/config/application.php')) {
    require_once $root_dir . '/config/application.php';
}

// Bootstrap WordPress
require_once ABSPATH . 'wp-settings.php';
